version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  search-tmdb:
    lang: node25
    handler: ./search-tmdb
    image: celerii/search-tmdb:latest
    secrets:
      - tmdb-access-token
  add-to-watchlist:
    lang: node25
    handler: ./add-to-watchlist
    image: celerii/add-to-watchlist:latest
    secrets:
      - couchdb-user
      - couchdb-password
  get-watchlist:
    lang: node25
    handler: ./get-watchlist
    image: celerii/get-watchlist:latest
    secrets:
      - couchdb-user
      - couchdb-password
