version: "3.9"

services:
  frontend:
    build: .
    image: yrtarexe-frontend:latest
    container_name: yrtarexe
    ports:
      - "3000:80"
    environment:
      # Remplacer par l'URL réelle de vos fonctions OpenFaaS
      BASE_URL: "http://127.0.0.1:8080/function"
    restart: unless-stopped
